### ISSUE TITLE
AttributeError in Colander with rubbish in request body 

### ISSUE THREAD

**Issue by leplatrem** [Cornices/cornice#268]
For example:

```
"\"{\\\"url\\\":\\\"http://fake\\\",\\\"title\\\":\\\"Fake\\\",\\\"added_by\\\":\\\"Fake\\\"}\""
```

Would crash the server :)

```
Traceback (most recent call last):
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/cornice-0.17-py2.7.egg/cornice/service.py", line 495, in wrapper
    validate_colander_schema(args['schema'], request)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/cornice-0.17-py2.7.egg/cornice/schemas.py", line 146, in validate_colander_schema
    _validate_fields('body', body)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/cornice-0.17-py2.7.egg/cornice/schemas.py", line 98, in _validate_fields
    data = webob.multidict.MultiDict(schema.unflatten(data))
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/cornice-0.17-py2.7.egg/cornice/schemas.py", line 80, in unflatten
    return self.colander_schema.unflatten(data)
  File "/Users/niko/readinglist/.venv/lib/python2.7/site-packages/colander-1.0-py2.7.egg/colander/__init__.py", line 1884, in unflatten
    paths = sorted(fstruct.keys())
AttributeError: 'str' object has no attribute 'keys'
```

**Comment by lavish205** [comment]
@leplatrem I want to work on this bug, looking forward for some instructions to start with.

**Comment by leplatrem** [comment]
Unfortunately, giving instructions on what to do would more or less imply finding the source of the problem.

You can look at the lines of code implied in the stacktrace, and test try to reproduce the exception with a piece of test!

**Comment by lavish205** [comment]
all I can understand is I have to de-serialize `str` into `dict` so that we can access the keys.
and for deserializing we can use `json.loads`

**Comment by leplatrem** [comment]
Should not happen with Cornice 2
