### ISSUE TITLE
Doing validation and filtering at class level error

### ISSUE THREAD

**Issue by hegazy** [Cornices/cornice#300]
This how I defined it
```
@users.get(klass=UserValidator, validators=('valid_token', ))
```
I defined the class as
```
class UserValidator(object):
 
     def __init__(self, request):
         self.request = request
 
     def valid_token(request):
         ...
```
This is the error trace
```
Traceback (most recent call last):
  File "/home/hegazy/penv/lib/python2.6/site-packages/waitress-0.8.9-py2.6.egg/waitress/channel.py", line 337, in service
    task.service()
  File "/home/hegazy/penv/lib/python2.6/site-packages/waitress-0.8.9-py2.6.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/home/hegazy/penv/lib/python2.6/site-packages/waitress-0.8.9-py2.6.egg/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/tweens.py", line 46, in excview_tween
    response = view_callable(exc, request)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/hegazy/penv/lib/python2.6/site-packages/pyramid-1.5.7-py2.6.egg/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/home/hegazy/penv/lib/python2.6/site-packages/cornice/service.py", line 564, in wrapper
    validator(request)
TypeError: 'str' object is not callable
```

After some debugging. I see that the condition` if 'klass' in args and not callable(view)` is not true and that results in `ob` being `None` and that is the problem because the validator is not mapped to the appropriate function.

**Comment by ametaireau** [comment]
The klass argument is used to resolve the **views**, and not the validators.

Validators should be callable, and that's what you're seing here. The string isn't resolved into a function / method and cannot be called as a function.

**Comment by hegazy** [comment]
Whaaaaat!
and what is this exactly? https://cornice.readthedocs.org/en/latest/validation.html#doing-validation-and-filtering-at-class-level

**Comment by ametaireau** [comment]
oh! Yeah I read the sourcecode too quickly. Apologies!

The code that's supposed to do this is [in the service.py file](https://github.com/mozilla-services/cornice/blob/master/cornice/service.py#L553-L560), so the documentation is correct.

Can you tell me if this patch solves your problem?

https://gist.github.com/95aa81c918cf9b9c8924

**Comment by hegazy** [comment]
No problem.
It solves this part, but arises another problem at
```
# If we have an object, it already has the request.
if ob: 
    response = view_()
else:
     response = view_(request)
```

I replaced it with 
```
response = view_(request)
```
and it works now. I don't know if this is right.

**Comment by Zatsugami** [comment]
I was having the same problem when I was trying to use dynamic schema provided by passed `klass` in services.

https://github.com/mozilla-services/cornice/blob/master/cornice/service.py#L551-L555
```python
# do schema validation
if 'schema' in args:
    validate_colander_schema(args['schema'], request)
elif hasattr(ob, 'schema'):
    validate_colander_schema(ob.schema, request)
```

Had no luck, but it was fairly easy to use `validate_colander_schema()` inside service implementation.

**Comment by leplatrem** [comment]
We changed the API for schema validators (see upgrading docs). Please, I know this issue was already closed once with no good reason, but don't hesitate to re-open if you still have problems with the new approach! Thanks, hope you understand ;)
