### ISSUE TITLE
Service validators doesn't work

### ISSUE THREAD

**Issue by sibukixxx** [Cornices/cornice#454]
I tried cornice validators.
This is

```
from cornice import Service
api_auth = Service(name='api.auth', path='/api/auth', description=description)

def validate_unique(request):
    name = request.params.get('name', '')

    if name == '':
        request.errors.add('url', 'name', 'user is not passed ...')
    else:
        name= { 'name':name, 'token': 'sample token'}
        request.validated['name'] = name

@api_auth.post(validators=unique)
def save(request):
    return {'result': 'ok'}
```

but it display error message `TypeError: unique() got an unexpected keyword argument 'renderer'`. 
Why?

```
2017-08-17 15:43:12,031 ERROR [waitress:341][waitress] Exception when serving /api/auth
Traceback (most recent call last):
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\waitress\channel.py", line 338, in service
    task.service()
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\waitress\task.py", line 169, in service
    self.execute()
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\waitress\task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\view.py", line 748, in invoke_exception_view
    reraise_(*exc_info)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\compat.py", line 147, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\router.py", line 249, in invoke_request
    response = handle_request(request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\view.py", line 744, in invoke_exception_view
    request_iface=request_iface.combined,
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\tweens.py", line 39, in excview_tween
    response = handler(request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\router.py", line 156, in handle_request
    view_name
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\config\views.py", line 181, in __call__
    return view(context, request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\pyramid\viewderivers.py", line 148, in _requestonly_view
    response = view(request)
  File "C:\Users\sample\dev\my-project\venv\lib\site-packages\cornice\service.py", line 484, in wrapper
    validator(request, **args)
TypeError: unique() got an unexpected keyword argument 'renderer'
```

**Comment by Natim** [comment]
`validators=validate_unique` ?

**Comment by sibukixxx** [comment]
Sorry, that's a typo.
The `unique` was correct.

**Comment by Natim** [comment]
Try `def validate_unique(request, *args, **kwargs):`

**Comment by leplatrem** [comment]
Yes, this is one of the changes for Cornice 2, the validators must accept kwargs
