### ISSUE TITLE
Is Cornice 3.2.0 backwards incompatible, or is there a bug in my application?

### ISSUE THREAD

**Issue by bowlofeggs** [Cornices/cornice#481]
Greetings! I noticed today that [an application I work on doesn't work with Cornice 3.2.0](https://github.com/fedora-infra/bodhi/issues/2258). I've not yet dug into the details of what the problem is, but I was curious if you thought this indicates a bug in my application, or if 3.2.0 might not be backwards compatible?

Here's a traceback (though it's pretty specific to my application and doesn't even involve Cornice):

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/hupper/worker.py", line 253, in worker_main
    func(*spec_args, **spec_kwargs)
  File "/usr/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/usr/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/usr/lib/python2.7/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/vagrant/bodhi/bodhi/server/__init__.py", line 358, in main
    return config.make_wsgi_app()
  File "/usr/lib/python2.7/site-packages/pyramid/config/__init__.py", line 1052, in make_wsgi_app
    self.commit()
  File "/usr/lib/python2.7/site-packages/pyramid/config/__init__.py", line 684, in commit
    self.action_state.execute_actions(introspector=self.introspector)
  File "/usr/lib/python2.7/site-packages/pyramid/config/__init__.py", line 1197, in execute_actions
    action = next(action_iter, None)
  File "/usr/lib/python2.7/site-packages/pyramid/config/__init__.py", line 1379, in resolveConflicts
    raise ConfigurationConflictError(conflicts)
ConfigurationConflictError: Conflicting configuration actions
  For: ('view', <class 'pyramid.httpexceptions.HTTPForbidden'>, '', None, 'd41d8cd98f00b204e9800998ecf8427e')
    Line 343 of file /home/vagrant/bodhi/bodhi/server/__init__.py:
        config.add_view('bodhi.server.security.login', context=HTTPForbidden)
    Line 430 of file /home/vagrant/bodhi/bodhi/server/views/generic.py:
        @view_config(context=Exception)
```

Downgrading to 3.1.0 gets things working again for me as a workaround, which was what prompted me to wonder if it was a backwards compatibility issue.

**Comment by ergo** [comment]
@bowlofeggs Looking at your exception this is the problem that you experience:

https://cornice.readthedocs.io/en/latest/faq.html#cornice-registers-exception-handlers-how-do-i-deal-with-it

Pyramid needs to somehow distinct the forbidden views `context=HTTPForbidden`, cornice tries to register it here: https://github.com/Cornices/cornice/blob/master/cornice/__init__.py#L90

**Comment by leplatrem** [comment]
@bowlofeggs please let us know if you could sort it out. Maybe there is some documentation to update (upgrade docs or something).

Thanks!

**Comment by ergo** [comment]
@bowlofeggs I was talking about automatic conflict resolution with pyramid developers you can quickly resolve this issue by moving `config.include('cornice')` inside `includeme()` for your application views, then it will overwrite conflicting config https://docs.pylonsproject.org/projects/pyramid/en/1.9-branch/narr/advconfig.html#automatic-conflict-resolution.

**Comment by bowlofeggs** [comment]
I'm travelling right now and have been for a while, so I haven't been able to look into this. I'm happy to close this ticket for now though under the assumption that I just need to fix my own code. I'll try to remember to report back here when I manage to figure that out!

**Comment by bowlofeggs** [comment]
Ha, I found what it was. Bodhi had two different views configured to handle ```HTTPForbidden```. The Pyramid error message did not make this clear, because it cited the line *below* one of the ```HTTPForbidden``` in Bodhi's generic.py:

```
    Line 430 of file /home/vagrant/bodhi/bodhi/server/views/generic.py:
        @view_config(context=Exception)
```

It was actually the line immediately before that line:

```
@view_config(context=HTTPForbidden)
```

Anyways, it turned out that the *other* ```HTTPForbidden``` view was the one I thought was sensible to drop, and dropping it got Bodhi to have the same API handling has it had with Cornice 3.1.0.

Bodhi now seems to work with Cornice 3.4.0:

https://github.com/fedora-infra/bodhi/pull/2376

Thanks for all your help.

**Comment by ergo** [comment]
Great that you got this resolved.
